version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - incption
    init: true

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - incption
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - DOMAIN_NAME=${DOMAIN_NAME}
    # ports:
    #   - 9000:9000
    restart: always
    init: true

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    networks:
      - incption
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    init: true

networks:
  incption:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/mrafik/Desktop/incep/all/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/mrafik/Desktop/incep/all/mariadb
      o: bind
