
FROM debian:buster

RUN apt-get update && apt-get install -y php7.3 php7.3-fpm php7.3-mysql mariadb-client curl sendmail

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
    && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

COPY ./tools/www.conf /etc/php/7.3/fpm/pool.d/www.conf
COPY ./wp-config.php /var/www/html/wordpress/
RUN chmod 644 /var/www/html/wordpress/wp-config.php 

WORKDIR /var/www/html/

COPY load.sh .

RUN chmod +x load.sh

RUN mkdir -p /run/php

ENTRYPOINT [ "./load.sh" ]

CMD ["php-fpm7.3", "-R", "-F"]