FROM debian:buster
RUN apt-get update && apt-get upgrade -y && apt-get -y  install nginx
COPY /tools/private.key /etc/ssl/
COPY /tools/certificate.crt /etc/ssl/
COPY /tools/index.html /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# RUN mkdir -p /etc/nginx/ssl
# RUN apt install OpenSSL -y
# RUN  openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=login.42.fr/UID=login"
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]
