#!/bin/bash

service mysql start

mariadb -u root -e "CREATE DATABASE <mrafik> ; CREATE USER '<mrafik>'@'%' IDENTIFIED BY '<mrafik>' ; REQUIRE NOT REGEXP 'admin|Admin|administrator|Administrator'; GRANT ALL PRIVILEGES ON <mrafik>.* TO '<mrafik>'@'%'; FLUSH PRIVILEGES;"


exec "$@"
